# Generated by Django 4.1.2 on 2022-10-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIC_LEARNING', '0005_delete_logindetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
